name: Deploy to GitHub Pages 🚀

on:
  # Triggers the workflow on pushes to the main branch
  push:
    branches:
      - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions to allow the GITHUB_TOKEN to create a deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recommended latest LTS version

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install
        
      # 4. Run the build command
      # This executes "tsc && vite build" which creates the production assets in the 'dist' directory.
      - name: Build project
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }} # Only deploy if pushing to the main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # The 'publish_branch' is the branch the assets will be pushed to (gh-pages is the common choice)
          publish_branch: gh-pages
          # The 'cname' is optional, but often useful if you are using a custom domain
          # cname: example.com 
